# Generated by Django 2.0.1 on 2018-04-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0003_auto_20180426_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginactivity',
            name='login_logout',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
