# Generated by Django 2.0.1 on 2018-04-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0005_terminalesmaestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='OT_multi_hasta20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=500)),
                ('precio', models.IntegerField(default=0)),
                ('canon', models.FloatField(default=0)),
                ('gama', models.CharField(max_length=20)),
                ('capta1', models.IntegerField()),
                ('capta2', models.IntegerField()),
                ('capta3', models.IntegerField()),
                ('capta4', models.IntegerField()),
                ('capta5', models.IntegerField()),
                ('porta1', models.IntegerField()),
                ('porta2', models.IntegerField()),
                ('porta3', models.IntegerField()),
                ('porta4', models.IntegerField()),
                ('porta5', models.IntegerField()),
            ],
        ),
    ]
