# Generated by Django 2.0.1 on 2018-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0006_ot_multi_hasta20'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisiones_datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.CharField(max_length=100)),
                ('comision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comisiones_iew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.CharField(max_length=100)),
                ('com10', models.CharField(max_length=100)),
                ('com1_9', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comisiones_multilinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.CharField(max_length=100)),
                ('capta', models.IntegerField()),
                ('porta', models.IntegerField()),
                ('terminal_movil_capta', models.IntegerField()),
                ('terminal_movil_porta', models.IntegerField()),
            ],
        ),
    ]
