# Generated by Django 2.0.1 on 2018-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0007_comisiones_datos_comisiones_iew_comisiones_multilinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisiones_iew',
            name='com10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comisiones_iew',
            name='com1_9',
            field=models.IntegerField(),
        ),
    ]
