# Generated by Django 2.0.1 on 2018-04-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0009_auto_20180427_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='OT_iew_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=500)),
                ('precio', models.IntegerField(default=0)),
                ('canon', models.FloatField(default=0)),
                ('gama', models.CharField(max_length=20)),
                ('precio1', models.IntegerField()),
                ('precio2', models.IntegerField()),
                ('precio3', models.IntegerField()),
                ('precio4', models.IntegerField()),
                ('dxc1', models.IntegerField()),
                ('dxc2', models.IntegerField()),
                ('dxc3', models.IntegerField()),
                ('dxc4', models.IntegerField()),
                ('dxc5', models.IntegerField()),
                ('nombre_foto', models.CharField(max_length=100)),
                ('gama_jorge', models.CharField(max_length=100)),
            ],
        ),
    ]
