# Generated by Django 2.0.1 on 2018-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0010_ot_iew_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='OT_multi_vap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=500)),
                ('precio', models.IntegerField(default=0)),
                ('canon', models.FloatField(default=0)),
                ('gama', models.CharField(max_length=20)),
                ('pago_unico_capta', models.IntegerField()),
                ('pago1', models.IntegerField()),
                ('cuota1', models.IntegerField()),
                ('pago2', models.IntegerField()),
                ('cuota2', models.IntegerField()),
                ('pago3', models.IntegerField()),
                ('cuota3', models.IntegerField()),
                ('pago4', models.IntegerField()),
                ('cuota4', models.IntegerField()),
                ('pago5', models.IntegerField()),
                ('cuota5', models.IntegerField()),
                ('dxc_pago_unico', models.IntegerField()),
                ('dxc1', models.IntegerField()),
                ('dxc2', models.IntegerField()),
                ('dxc3', models.IntegerField()),
                ('dxc4', models.IntegerField()),
                ('dxc5', models.IntegerField()),
                ('nombre_foto', models.CharField(max_length=100)),
                ('gama_jorge', models.CharField(max_length=100)),
            ],
        ),
    ]
