# Generated by Django 2.0.1 on 2018-04-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0011_ot_multi_vap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='cuota1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='cuota2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='cuota3',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='cuota4',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='cuota5',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='pago1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='pago2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='pago3',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='pago4',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ot_multi_vap',
            name='pago5',
            field=models.CharField(max_length=4),
        ),
    ]
