# Generated by Django 2.0.1 on 2018-05-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0012_auto_20180430_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='OT_iew_vap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=500)),
                ('precio', models.IntegerField(default=0)),
                ('canon', models.FloatField(default=0)),
                ('gama', models.CharField(max_length=20)),
                ('meses_cuota', models.IntegerField(default=0)),
                ('pago_unico_capta', models.IntegerField()),
                ('pago1', models.CharField(max_length=4)),
                ('cuota1', models.CharField(max_length=4)),
                ('pago2', models.CharField(max_length=4)),
                ('cuota2', models.CharField(max_length=4)),
                ('pago3', models.CharField(max_length=4)),
                ('cuota3', models.CharField(max_length=4)),
                ('pago4', models.CharField(max_length=4)),
                ('cuota4', models.CharField(max_length=4)),
                ('dxc_pago_unico', models.IntegerField()),
                ('dxc1', models.IntegerField()),
                ('dxc2', models.IntegerField()),
                ('dxc3', models.IntegerField()),
                ('dxc4', models.IntegerField()),
                ('nombre_foto', models.CharField(max_length=100)),
                ('gama_jorge', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ot_iew_sub',
            name='dxc5',
        ),
    ]
