# Generated by Django 2.0.1 on 2018-05-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0016_auto_20180505_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisiones_conecta',
            name='valor_volumen',
            field=models.BooleanField(default=False),
        ),
    ]
