# Generated by Django 2.0.1 on 2018-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0019_comisiones_conecta_columna_prima_operaciones_oficina_plus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisiones_prima_operaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño_pago', models.IntegerField(default=0)),
                ('base', models.FloatField(default=0)),
                ('acelerador_conecta_1', models.FloatField(default=0)),
                ('acelerador_conecta_2', models.FloatField(default=0)),
                ('acelerador_conecta_3', models.FloatField(default=0)),
                ('acelerador_conecta_4', models.FloatField(default=0)),
                ('acelerador_oplus_propia', models.FloatField(default=0)),
                ('acelerador_oplus_indirecta_1a', models.FloatField(default=0)),
                ('acelerador_iew_pro_1', models.FloatField(default=0)),
                ('acelerador_iew_pro_2', models.FloatField(default=0)),
                ('acelerador_iew_pro_3', models.FloatField(default=0)),
                ('comision_operaciones_0', models.FloatField(default=0)),
            ],
        ),
    ]
