# Generated by Django 2.0.1 on 2018-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0020_comisiones_prima_operaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionesConfiGuardadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=300)),
                ('cif_nif', models.CharField(max_length=9)),
                ('n_lineas_diferntes', models.IntegerField()),
                ('total_lineas', models.IntegerField()),
                ('usuario', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nlineas', models.IntegerField()),
                ('tarifa', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
                ('paquete_datos', models.CharField(max_length=50)),
                ('cv', models.CharField(max_length=10)),
                ('mfo', models.CharField(max_length=10)),
                ('mmodelo_subvecion', models.CharField(max_length=10)),
                ('terminal', models.CharField(max_length=500)),
                ('comision_voz', models.FloatField(default=0)),
                ('comision_datos', models.FloatField(default=0)),
                ('comision_terminal', models.FloatField(default=0)),
                ('comision_sva', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('dxc', models.FloatField(default=0)),
                ('comision_fija', models.FloatField(default=0)),
                ('cuota', models.FloatField(default=0)),
                ('pvp', models.FloatField(default=0)),
                ('rentabilidad_porLinea', models.FloatField(default=0)),
                ('totalUpfront_por_linea', models.FloatField(default=0)),
                ('prima_opex_base', models.FloatField(default=0)),
                ('prima_opex_conecta', models.FloatField(default=0)),
                ('prima_opex_iew', models.FloatField(default=0)),
                ('prima_volumen_movil', models.FloatField(default=0)),
                ('prima_volumen_fijo', models.FloatField(default=0)),
                ('foto', models.CharField(max_length=300)),
                ('escliente_oficinaPlus', models.BooleanField(default=0)),
                ('esclientevalor_volumen', models.BooleanField(default=0)),
                ('gama_jorge', models.CharField(max_length=100)),
                ('aviso', models.CharField(max_length=800)),
            ],
        ),
    ]
