# Generated by Django 2.0.1 on 2018-05-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0023_auto_20180510_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacionesconfiguardadas',
            old_name='n_lineas_diferntes',
            new_name='n_lineas_diferentes',
        ),
    ]
