# Generated by Django 2.0.1 on 2018-05-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0024_auto_20180510_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesconfiguardadas',
            name='cuota',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='operacionesconfiguardadas',
            name='pvp',
            field=models.CharField(max_length=10),
        ),
    ]
