# Generated by Django 2.0.1 on 2018-05-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confi', '0025_auto_20180510_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacionesconfiguardadas',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='operacionesconfiguardadas',
            old_name='totalUpfront_por_linea',
            new_name='totalUpfront',
        ),
    ]
